version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  openfaas-node12-react:
    lang: node12
    handler: ./function
    image: janakasteph/openfaas-node12-react
    environment:
      write_debug: true